# ------------------------------------------------------------------------------
# haproxy helm chart that wraps the official chart repository
# ------------------------------------------------------------------------------
apiVersion: v2
name: meowhq-haproxy
description: A Helm chart for haproxy
type: application
version: 1.1.0
dependencies:
  - name: haproxy
    version: 0.10.11
    repository: "https://charts.bitnami.com/bitnami"
