# ------------------------------------------------------------------------------
# redis helm chart that wraps the official chart repository
# ------------------------------------------------------------------------------
apiVersion: v2
name: meowhq-redis
description: A Helm chart for redis
type: application
version: 1.6.1
dependencies:
  - name: redis
    version: 18.4.0
    repository: "https://charts.bitnami.com/bitnami"
