# ------------------------------------------------------------------------------
# redis helm chart that wraps the official chart repository
# ------------------------------------------------------------------------------
apiVersion: v2
name: meowhq-redis
description: A Helm chart for redis
type: application
version: 1.19.0
dependencies:
  - name: redis
    version: 20.7.1
    repository: "https://charts.bitnami.com/bitnami"
