apiVersion: v2
name: meowhq-mysql
description: A Helm chart for MySQL
type: application
version: 0.1.1
dependencies:
  - name: mysql
    version: 9.23.0
    repository: "https://charts.bitnami.com/bitnami"
