# ------------------------------------------------------------------------------
# values for nginx
# ------------------------------------------------------------------------------

nginx:
  image:
    # repository: bitnami/nginx
    # tag: 1.25.2-debian-11-r37
    tag: 1.25.2-debian-11-r40
  service:
    type: ClusterIP



