apiVersion: v2
name: meowhq-vault
description: A Helm chart for vault
type: application
version: 0.5.1
dependencies:
  - name: vault
    version: 0.27.0
    repository: https://helm.releases.hashicorp.com
