# ------------------------------------------------------------------------------
# argocd helm chart that wraps the official chart repository
# ------------------------------------------------------------------------------
apiVersion: v2
name: meowhq-argocd
description: A Helm chart for argocd
type: application
version: 0.8.1
dependencies:
  - name: argo-cd
    version: 5.51.6
    repository: "https://argoproj.github.io/argo-helm"
